.tx/config
=> change resource name to lowercase

templates/content/index.php
=> Grammar fix

src/js/main.js
=> Fixed typo

templates/content/configuration.php
=> Fixed grammar

templates/content/index.php
=> Improved source strings

templates/content/changelog.php
=> Changed wording

lib/Db/Bdd.php
=> l10n: mail to email

src/js/pdf.js
Translator's report from Transifex.
=> l10n: Correct spelling

src/js/pdf.js
Spelling unification in Transifex.
=> l10n: Spelling unification

templates/content/changelog.php
=> l10n: Improved grammar

src/js/pdf.js
=> l10n: Removed blank

templates/content/changelog.php, templates/content/configuration.php
=> l10n: Fixed issues reported at Transifex

lib/Db/Bdd.php
=> l10n: Fixed grammar

templates/content/changelog.php, templates/content/configuration.php
A more selected description of the function setting.
=> l10n: Improve styling

templates/content/changelog.php
Change from "Release" to "Releases" and add dots at the end of the sentence for feature descriptions. Solution of issue #149.
=> l10n: Add dots and replace word

templates/navigation/index.php
=> l10n: Change to plural

templates/content/devisshow.php, templates/content/factureshow.php
1. Re-styling a sentence as a description for a function.
2. Removal of parentheses which are redundant since this is a complete sentence.
=> l10n: Re-style sentence and remove parentheses

src/js/modules/ajaxRequest.mjs, templates/content/changelog.php, templates/settings/admin.php
1. Extracting the space character and line break outside the text string.
2. Change the position of the dot at the end of the sentence.
3. Improve the style of the sentence - _reported by the translator in Transifex_.
=> l10n: Correct text strings

templates/content/changelog.php, templates/content/legalnotice.php
=> l10n: Remove space

lib/Db/Bdd.php
Fix the issue https://github.com/baimard/gestion/issues/427
=> postgresql compatibility

src/js/pdf.js
=> chore(i18n): Changed source strings to english
